/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.views.vehicles;

import com.mycompany.views.vehicles.AddNewVehicle;
import com.mycompany.dao.CarroDao;
import com.mycompany.dao.MotoDao;
import com.mycompany.dao.UtilitarioDao;
import com.mycompany.impl.CarroDaoImpl;
import com.mycompany.impl.MotoDaoImpl;
import com.mycompany.impl.UtilDaoImpl;
import com.mycompany.mecservs.Dashboard;
import java.awt.Color;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sirval
 */
public class AllVehicles extends javax.swing.JPanel {

    /**
     * Creates new form AllVehicles
     */
    
    
    public AllVehicles() {
        initComponents();
         initStyles();
         loadVehicles();
    }
    
      private void initStyles(){
      btnAdicionar.setForeground(Color.BLACK);
      btnFiltrar.setForeground(Color.BLACK);
      //Alinhar o texto ao centro
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(SwingConstants.CENTER);
        
        // Aplica o alinhamento nas colunas
        for (int i = 0; i < tableContent.getColumnCount(); i++) {
            tableContent.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
        }
      }
      
      public static void loadVehicles(){ //Não esta listando na pagina principal
          try{
              DefaultTableModel model = (DefaultTableModel) tableContent.getModel();
              if( CarroDaoImpl.carrosDisponiveis != null){
                  CarroDaoImpl.carrosDisponiveis.forEach((u)->model.addRow(new Object[]{u.getTipo(),u.getPlaca(),u.getModelo(),u.getAnoFabric()}));
              }
              if(MotoDaoImpl.motosDisponiveis != null){
                  MotoDaoImpl.motosDisponiveis.forEach((u)->model.addRow(new Object[]{u.getTipo(),u.getPlaca(),u.getModelo(),u.getAnoFabric()}));  
              }
              if( UtilDaoImpl.utilsDisponiveis != null){
                   UtilDaoImpl.utilsDisponiveis.forEach((u)->model.addRow(new Object[]{u.getTipo(),u.getPlaca(),u.getModelo(),u.getAnoFabric()}));  
              }  
          
          }catch(Exception e){
              System.out.println("Nao foi possivel listar os veiculos." + e.getMessage());
          }
      }
      
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableContent = new javax.swing.JTable();
        mesagemAlerta = new javax.swing.JLabel();
        btnAdicionar = new javax.swing.JButton();
        btnFiltrar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        tableContent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Categoria", "Placa", "Modelo", "AnoFabric"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableContent.setEnabled(false);
        jScrollPane1.setViewportView(tableContent);
        if (tableContent.getColumnModel().getColumnCount() > 0) {
            tableContent.getColumnModel().getColumn(0).setResizable(false);
            tableContent.getColumnModel().getColumn(1).setResizable(false);
            tableContent.getColumnModel().getColumn(2).setResizable(false);
            tableContent.getColumnModel().getColumn(3).setResizable(false);
        }

        mesagemAlerta.setBackground(new java.awt.Color(255, 255, 255));
        mesagemAlerta.setForeground(new java.awt.Color(255, 0, 0));
        mesagemAlerta.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        mesagemAlerta.setText("*");
        mesagemAlerta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mesagemAlertaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mesagemAlertaMouseExited(evt);
            }
        });

        btnAdicionar.setText("ADICIONAR");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        btnFiltrar.setText("FILTRAR");
        btnFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 738, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 472, Short.MAX_VALUE)
                        .addComponent(btnAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mesagemAlerta, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(mesagemAlerta, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        Dashboard.ShowJPanel(new AddNewVehicle());
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void mesagemAlertaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mesagemAlertaMouseEntered
       this.mesagemAlerta.setText("Para acessar todos os atributos especificos de um tipo de Automovel, filtre pelo mesmo.");
       this.mesagemAlerta.putClientProperty( "FlatLaf.style", "font: 14 $light.font" );
       this.mesagemAlerta.setHorizontalAlignment(SwingConstants.LEFT);
    }//GEN-LAST:event_mesagemAlertaMouseEntered

    private void mesagemAlertaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mesagemAlertaMouseExited
        this.mesagemAlerta.setText("*");
       this.mesagemAlerta.setHorizontalAlignment(SwingConstants.TRAILING);
    }//GEN-LAST:event_mesagemAlertaMouseExited

    private void btnFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarActionPerformed
       Dashboard.ShowJPanel(new FIlterOptions());
    }//GEN-LAST:event_btnFiltrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnFiltrar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel mesagemAlerta;
    private static javax.swing.JTable tableContent;
    // End of variables declaration//GEN-END:variables
}
