/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.views.vehicles;

import com.mycompany.impl.CarroDaoImpl;
import com.mycompany.impl.MotoDaoImpl;
import com.mycompany.impl.UtilDaoImpl;
import com.mycompany.views.vehicles.AllVehicles;
import com.mycompany.views.vehicles.AllUtils;
import com.mycompany.views.vehicles.AllMotos;
import com.mycompany.views.vehicles.AllCars;
import com.mycompany.mecservs.Dashboard;
import java.awt.Color;

/**
 *
 * @author Sirval
 */
public class FIlterOptions extends javax.swing.JPanel {

    private AllVehicles allVehicles = new AllVehicles();
    private AllCars allCars = new AllCars();
    private AllMotos allMotos = new AllMotos();
    private AllUtils allUtils = new AllUtils();
    /**
     * Creates new form FIlterOptions
     */
    public FIlterOptions() {
        initComponents();
        initStyles();
    }
    private void initStyles(){
    btnCarros.setForeground(Color.BLACK);
    btnMotos.setForeground(Color.BLACK);
    btnUtil.setForeground(Color.BLACK);
    btnVoltar.setForeground(Color.BLACK);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnCarros = new javax.swing.JButton();
        btnMotos = new javax.swing.JToggleButton();
        btnUtil = new javax.swing.JToggleButton();
        btnVoltar = new javax.swing.JToggleButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(43, 19, 133), 1, true));

        btnCarros.setText("CARROS");
        btnCarros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarrosActionPerformed(evt);
            }
        });

        btnMotos.setText("MOTOS");
        btnMotos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMotosActionPerformed(evt);
            }
        });

        btnUtil.setText("UTÍLITARIOS");
        btnUtil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUtilActionPerformed(evt);
            }
        });

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCarros, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMotos, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUtil, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(btnCarros, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMotos, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnUtil, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVoltar, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
      Dashboard.ShowJPanel(allVehicles);
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnCarrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarrosActionPerformed
        Dashboard.ShowJPanel(allCars);
        if(CarroDaoImpl.carrosDisponiveis != null){
             allCars.loadCars();
        }
    }//GEN-LAST:event_btnCarrosActionPerformed

    private void btnMotosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMotosActionPerformed
       Dashboard.ShowJPanel(allMotos);
       if(MotoDaoImpl.motosDisponiveis != null){
             allMotos.loadMotos();
       }
    }//GEN-LAST:event_btnMotosActionPerformed

    private void btnUtilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUtilActionPerformed
      Dashboard.ShowJPanel(allUtils);
      if(UtilDaoImpl.utilsDisponiveis != null){
           allUtils.loadUtils();
      } 
    }//GEN-LAST:event_btnUtilActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCarros;
    private javax.swing.JToggleButton btnMotos;
    private javax.swing.JToggleButton btnUtil;
    private javax.swing.JToggleButton btnVoltar;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
