/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.views.start;

import java.awt.Color;

/**
 *
 * @author Sirval
 */
public class Start extends javax.swing.JPanel {

    /**
     * Creates new form Star
     */
      public Start() {
        initComponents();
        initStyles();
    }
    private void initStyles(){
       txtInical.putClientProperty( "FlatLaf.style", "font: 16 $light.font" );
       txtInical.setForeground(Color.BLACK);
       txtDescricaoTrabalho.putClientProperty( "FlatLaf.style", "font: 16 $light.font" );
       txtDescricaoTrabalho.setForeground(Color.BLACK);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtInical = new javax.swing.JTextArea();
        txtDescricaoTrabalho = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(750, 430));

        txtInical.setEditable(false);
        txtInical.setColumns(20);
        txtInical.setRows(5);
        txtInical.setText("O MecServs é um software pensado em \nautomatizar os processos de uma oficina mecânica, buscando melhorar a eficiencia do processo e\nevitar o trabalho repetitivo. Desta maneira, sendo um software com funcionalidades simples, \npode agregar muito na vida e no dia-a-dia do usuario final, sendo este o real motivo de sua concepção.");
        txtInical.setBorder(null);
        txtInical.setFocusable(false);
        txtInical.setOpaque(false);
        txtInical.setRequestFocusEnabled(false);
        txtInical.setSelectionColor(new java.awt.Color(255, 255, 255));
        txtInical.setVerifyInputWhenFocusTarget(false);

        txtDescricaoTrabalho.setEditable(false);
        txtDescricaoTrabalho.setColumns(20);
        txtDescricaoTrabalho.setRows(5);
        txtDescricaoTrabalho.setText("A primeira versão desta implementação está sendo realizada como trabalho final da matéria de\n Programação Orientada a Objetos, para a turma do 4° semestre do curso de Análise e \nDesenvolvimento de Sistemas da Universidade Católica Dom Bosco(UCDB).\n");
        txtDescricaoTrabalho.setBorder(null);
        txtDescricaoTrabalho.setFocusable(false);
        txtDescricaoTrabalho.setOpaque(false);
        txtDescricaoTrabalho.setRequestFocusEnabled(false);
        txtDescricaoTrabalho.setSelectionColor(new java.awt.Color(255, 255, 255));
        txtDescricaoTrabalho.setVerifyInputWhenFocusTarget(false);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/engrenagem.png"))); // NOI18N
        jLabel1.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDescricaoTrabalho)
                    .addComponent(txtInical, javax.swing.GroupLayout.DEFAULT_SIZE, 725, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtInical, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtDescricaoTrabalho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextArea txtDescricaoTrabalho;
    private javax.swing.JTextArea txtInical;
    // End of variables declaration//GEN-END:variables
}
